### ISSUE TITLE
Infinite looping in Malayalm stemming

### ISSUE THREAD

**Issue by kavitharaju** [libindic/indicstemmer#12]
When the word "പൊന്ന്" is given, the Malayalam stemmer goes into an infinite loop. When the break statement in line 113 was removed it solved the issue.

**Comment by santhoshtr** [comment]
Malayalam stemmer won't get any updates in this project. A larger Malayalam morphology analyser is in active development. See https://github.com/smc/mlmorph

**Comment by kavitharaju** [comment]
Thank you for pointing it out
